export const DETERMINERS = ["a", "the", "this", "that"];

export const PREPOSITIONS = [
  "about",
  "after",
  "against",
  // "along",
  "among",
  // "around",
  // "at",
  // "because of",
  "before",
  "behind",
  "below",
  "beneath",
  // "beside",
  // "besides",
  // "between",
  // "beyond",
  "by",
  "concerning",
  "despite",
  // "down",
  "during",
  "except",
  "excepting",
  "for",
  "from",
  "in spite of",
  "in",
  "inside",
  "instead of",
  "into",
  "like",
  "near",
  "of",
  "off",
  "on",
  "onto",
  "out",
  "outside",
  "over",
  "past",
  "regarding",
  "since",
  "through",
  "throughout",
  "to",
  "toward",
  "under",
  "underneath",
  // "until",
  // "up to",
  // "up",
  "upon",
  "with regard to",
  "with respect to",
  "with",
  "within",
  "without",
  // 'but'
];

export const NOUNS = [
  { nn: "Red Bull", nns: "Red Bulls" },
  { nn: "agitator", nns: "agitators" },
  { nn: "art", nns: "arts" },
  { nn: "bat", nns: "bats" },
  { nn: "bicycle", nns: "bicycles" },
  { nn: "bird", nns: "birds" },
  { nn: "board of directors", nns: "boards of directors" },
  { nn: "capitalist", nns: "capitalists" },
  { nn: "car", nns: "cars" },
  { nn: "cat", nns: "cats" },
  { nn: "communist", nns: "communists" },
  { nn: "computer", nns: "computers" },
  { nn: "dog", nns: "cats" },
  { nn: "fact", nns: "facts" },
  { nn: "family", nns: "families" },
  { nn: "government", nns: "governments" },
  { nn: "history", nns: "histories" },
  { nn: "idea", nns: "ideas" },
  { nn: "keyboard", nns: "keyboards" },
  { nn: "map", nns: "maps" },
  { nn: "method", nns: "methods" },
  { nn: "person", nns: "people" },
  { nn: "problem", nns: "problems" },
  { nn: "reporter", nns: "reporters" },
  { nn: "robot", nns: "robots" },
  { nn: "socialist", nns: "socialists" },
  { nn: "theory", nns: "theories" },
  { nn: "trunk", nns: "trunks" },
  { nn: "vehicle", nns: "vehicles" },
  { nn: "village", nns: "villages" },
  { nn: "way", nns: "ways" },
  { nn: "world", nns: "worlds" },
  { nn: "year", nns: "years" },
];

export const ADJECTIVES = [
  "agreeable",
  "amusing",
  "ashy",
  "attractive",
  "bad",
  "bald",
  "beautiful",
  "big",
  "black",
  "blue",
  "boisterous",
  "brave",
  "busy",
  "calm",
  "chubby",
  "clean",
  "colossal",
  "convivial",
  "delicious",
  "dextrous",
  "disastrous",
  "drab",
  "elegant",
  "enjoyable",
  "entertaining",
  "evil",
  "fancy",
  "fast",
  "fun",
  "good",
  "gray",
  "great",
  "green",
  "happy",
  "helpless",
  "high",
  "huge",
  "icy",
  "immense",
  "itchy",
  "jolly",
  "large",
  "lemon",
  "lively",
  "magnificent",
  "mango",
  "merry",
  "microscopic",
  "miniature",
  "obedient",
  "obvious",
  "orange",
  "petite",
  "plain",
  "pleasant",
  "plump",
  "puny",
  "purple",
  "red",
  "salmon",
  "scrawny",
  "silly",
  "skinny",
  "slow",
  "snowy",
  "sour",
  "sticky",
  "stocky",
  "teeny",
  "terrible",
  "tiny",
  "white",
  "yellow",
  "yummy",
];

export const VERBS = [
  { vb: "agree", vbz: "agrees", transitive: false, intransitive: true },
  { vb: "appear", vbz: "appears", transitive: false, intransitive: true },
  { vb: "arrive", vbz: "arrives", transitive: false, intransitive: true },
  { vb: "attack", vbz: "attacks", transitive: true, intransitive: false },
  { vb: "become", vbz: "becomes", transitive: true, intransitive: false },
  { vb: "break", vbz: "breaks", transitive: true, intransitive: false },
  { vb: "consume", vbz: "consumes", transitive: true, intransitive: false },
  { vb: "continue", vbz: "continues", transitive: false, intransitive: true },
  { vb: "cry", vbz: "cries", transitive: false, intransitive: true },
  { vb: "destroy", vbz: "destroys", transitive: true, intransitive: false },
  { vb: "die", vbz: "dies", transitive: false, intransitive: true },
  { vb: "draw", vbz: "draws", transitive: true, intransitive: false },
  { vb: "drink", vbz: "drinks", transitive: true, intransitive: false },
  { vb: "eat", vbz: "eats", transitive: true, intransitive: false },
  { vb: "exist", vbz: "exists", transitive: false, intransitive: true },
  { vb: "feel", vbz: "feels", transitive: true, intransitive: false },
  { vb: "find", vbz: "finds", transitive: true, intransitive: false },
  { vb: "float", vbz: "floats", transitive: false, intransitive: true },
  { vb: "follow", vbz: "follows", transitive: true, intransitive: false },
  { vb: "forgive", vbz: "forgives", transitive: true, intransitive: false },
  { vb: "grow", vbz: "grows", transitive: false, intransitive: true },
  { vb: "happen", vbz: "happens", transitive: false, intransitive: true },
  { vb: "leave", vbz: "leaves", transitive: false, intransitive: true },
  { vb: "lie", vbz: "lies", transitive: false, intransitive: true },
  { vb: "listen", vbz: "listens", transitive: false, intransitive: true },
  { vb: "need", vbz: "needs", transitive: true, intransitive: false },
  { vb: "panic", vbz: "panics", transitive: false, intransitive: true },
  { vb: "smile", vbz: "smiles", transitive: false, intransitive: true },
  { vb: "steal", vbz: "steals", transitive: true, intransitive: false },
  { vb: "surprise", vbz: "surprises", transitive: true, intransitive: false },
  { vb: "talk", vbz: "talks", transitive: false, intransitive: true },
  { vb: "throw", vbz: "throws", transitive: true, intransitive: false },
  { vb: "work", vbz: "works", transitive: true, intransitive: false },
  { vb: "work", vbz: "works", transitive: false, intransitive: true },
  { vb: "yell", vbz: "yells", transitive: false, intransitive: true },
];

export const TRANSITIVE_VERBS = VERBS.filter((v) => v.transitive);
export const INTRANSITIVE_VERBS = VERBS.filter((v) => v.intransitive);

export const COORDINATING_CONJUNCTIONS = [
  "and",
  "but",
  "for",
  "nor",
  "or",
  "yet",
  // "so",
];
